blank_issues_enabled: true
contact_links:
  - name: Security Contact
    about: Please report security vulnerabilities to ahmdparsh129@gmail.com
  - name: Questions and discussions
    url: https://github.com/KomeilParseh/Sansorchi/discussions
    about: Discuss questions about your code on our Discord chat.
