blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: mailto:ahmdparsh129@gmail.com
    about: Do not report security issues publicly. Email our security contact.
  - name: Questions and discussions
    url: https://github.com/KomeilParseh/Sansorchi/discussions
    about: Discuss questions about your code on our Discord chat.
