name: Feature Request
description: Suggest an idea or ask for a feature that you would like to have in sansorchi
title: "[Feature]: "
labels: [enhancement]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in sansorchi! 🚀

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Help
    attributes:
      label: Commit to Help
      description: What exactly do you want it to do?
      placeholder: Tell us what you see!
      value: "What does this feature want to do?"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KomeilParseh/Sansorchi/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
