name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "test Sansorchi"
          extra-pylint-options: "disable=W0102,C0103"
