name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: KomeilParseh/python-lint@1
        with:
          python-root-list: "test Sansorchi"
          extra-pylint-options: "--disable=W0102,C0103"
          extra-black-options: "."
